### ISSUE TITLE
illegal reflexive access error, using jdk-10.0.1 on MacOS

### ISSUE THREAD

**Issue by dacase** [mjschnie/ffx#5]
Hi Mike:  I'm finally(!) getting around to trying to learn about ffx, but had trouble getting started.

I'm on MacOS, and JAVA_HOME is /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home.

I used mvn to install ffx from github, and (separately) downloaded the ffx-1.0.0-beta.bin.tar file.  Both gave the problem in the subject header, when trying the run the first example script.  Uninstalling jdk10 and going back to jdk1.8.0_171.jdk solved the problem.  But I'm not sure that is the right thing to be doing, since there might be a better solution.

If you go to the Oracle site (e.g. by following the link on the ffx website), it puts JDK 10 as the "latest release" and the one they offer first.  Other java-clueless people (like me) might be helped if indeed saying "java version 1.8 or later" is not in fact always the best thing to do.

....thanks....dave

**Comment by jacob-litman** [comment]
Hello Prof. Case,

Short version: I suspect what we'll do is stick a warning in our installation instructions to use JDK 1.8 or earlier, until the more fundamental issues are resolved. It should also be possible to stick a warning message into the launch scripts.

The issue has to do with Groovy performing illegal reflective accesses, something that triggers a warning in JDK 1.9 and is by default disallowed in JDK 10.

Unfortunately, the flags one needs to set to permit illegal accesses aren't recognized by versions 1.8 or earlier, causing JDK 1.8 to refuse to start up. I took a stab at auto-detecting JDK 1.9+ and adding the flags only if that were true, but for some reason I couldn't get the flags to work.

Thank you,
Jacob Litman

**Comment by dacase** [comment]
Thanks for your quick reply!  As little as I know about Java, I know even less about Groovy  :-)  As far as I am concerned, you can close the issue if you want.

....dac

**Comment by jacob-litman** [comment]
This is where we are right now:

There are additional errors in Java 10, that Prof. Schnieders is trying to track down, unrelated to the illegal-access warnings.

We think it technically works with Java 9, albeit with warnings.

Unless the unit tests fail, I will soon be pushing a commit that detects unsupported Java versions in the ffx/ffxc Bash scripts using awk and sed if available, as well as commenting on it in Readme.md. If awk and sed are unavailable, or using the Windows batch files, we will simply warn that we could not autodetect JDK compatibility, and recommend JDK 1.8.

Thank you,
Jacob Litman

**Comment by jacob-litman** [comment]
It appears to work on JDK 10 as of this commit: 223d469cba3bbfe16af8e1fee499be9fe002b3b2

JDK 11+ support is a work in progress.

**Comment by jacob-litman** [comment]
Closing this issue, as JDK 10 is supported. JDK 11, as I understand, requires waiting for Groovy to be compatible with JDK 11.
